spring: 
  profile:
    active:
    - dev
---
spring: 
  profile: dev
  application:
    name: microservicecloud-config-aidata-dev
---
spring: 
  profile: test
  application:
    name: microservicecloud-config-aidata-test